version: '3.8'

services:
  server:
    restart: always
    build: server
    ports:
      - '80:80'
    container_name: mirea_rschir_first_server
  db:
    build: db
    restart: always
    ports:
      - '3307:3306'
    container_name: mirea_rschir_first_db
