version: "3.8"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: db
      MYSQ_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: appDB
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  server:
    build: ./server
    restart: always
    volumes:
      - ./server:/var/www/html/
    ports:
      - "80:80"