version: "3.8"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
    ports:
      - "3307:3306"
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/src:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    links:
      - db
      - apache
  apache:
    build: ./apache-php
    restart: always
    volumes:
      - ./apache-php/src:/var/www/html-dynamic/
      - ./apache-php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - db
  redis:
    container_name: back_practice_redis
    image: redis
    ports:
      - '6379:6379'